---
- name: configure nxos1 switch for pyats lab
  gather_facts: no
  hosts: nxos1

  tasks:
    - name: verify ssh is up and running
      wait_for:
        port: 4822
        timeout: 10

    - name: enable feature ospf
      nxos_feature:
        feature: ospf
        state: enabled

    - name: enable feature bgp
      nxos_feature:
        feature: bgp
        state: enabled

    - name: enable interfaces
      nxos_interface:
        name: "{{ item.name }}"
        admin_state: up
        mode: layer3
      with_items: "{{ interfaces }}"
      when: "'Ethernet' in  item.name"

    - name: configure IP addresses on interfaces
      nxos_l3_interface:
        name: "{{ item.name }}"
        ipv4: "{{ item.ipv4 }}/{{ item.prefix_len }}"
        state: present
      with_items: "{{ interfaces }}"

    - name: enable router ospf
      nxos_ospf: 
       ospf: "{{ protocols.ospf.name }}"
       state: present

    - name: configure ospf interfaces
      nxos_interface_ospf:
        interface: "{{ item.name }}"
        ospf: "{{ protocols.ospf.name }}"
        area: 0.0.0.0
        network: point-to-point
        state: present
      with_items: "{{ interfaces }}"

    - name: configure static routes
      nxos_static_route:
        prefix: "{{ item.prefix }}"
        next_hop: "{{ item.next_hop }}"
      with_items: "{{ protocols.static }}"


    - name: save configuration
      nxos_config:
         save_when: always
