---
- name: configure iosxe1 switch for pyats lab
  gather_facts: no
  hosts: iosxe1

  tasks:
    - name: verify ssh is up and running
      wait_for:
        port: 4922
        timeout: 10

    - name: set hostname
      ios_system:
        hostname: "{{ inventory_hostname }}"

    - name: enable lldp
      ios_lldp:
        state: present

    - name: enable interfaces
      ios_interface:
        name: "{{ item.name }}"
        enabled: true
        state: up
      with_items: "{{ interfaces }}"
      when: "'Ethernet' in  item.name"

    - name: configure IP addresses on interfaces
      ios_l3_interface:
        name: "{{ item.name }}"
        ipv4: "{{ item.ipv4 }}/{{ item.prefix_len }}"
        state: present
      with_items: "{{ interfaces }}"

    - name: configure static routes
      ios_static_route:
        prefix: "{{ item.prefix | ipaddr('network') }}"
        mask: "{{ item.prefix | ipaddr('netmask') }}"
        next_hop: "{{ item.next_hop }}"
      with_items: "{{ protocols.static }}"

    - name: configure prefix-list
      ios_config:
        lines:
          - ip prefix-list STATIC permit {{ item.prefix }}
      with_items: "{{ protocols.static }}"
      ignore_errors: yes

    - name: configure route-map
      ios_config:
        parents: route-map STATIC permit 10
        lines:
          - match ip address prefix-list STATIC

    - name: enable router OSPF
      ios_config:
        lines:
          - router ospf {{ protocols.ospf.name }}
      
    - name: enable OSPF on interfaces
      ios_config:
        lines:
          - ip ospf network point-to-point
          - ip ospf {{ protocols.ospf.name }} area 0.0.0.0
        parents: interface {{ item.name }}
      with_items: "{{ interfaces }}"

    - name: enable BGP router
      ios_bgp:
        config:
          bgp_as: "{{ protocols.bgp.asn }}"
          router_id: "{{ item.ipv4 }}"
      loop: "{{ lookup('list', interfaces) }}"
      when: "'loopback' in item.name"

    - name: configure BGP neighbors
      ios_bgp:
        config:
          bgp_as: "{{ protocols.bgp.asn }}"
          neighbors:
            - neighbor: "{{ item.ipv4 }}"
              remote_as: "{{ item.asn }}"
              update_source: "{{ item.update_source}}"
          address_family:
            - afi: ipv4
              safi: unicast
              neighbors:
                - neighbor: "{{ item.ipv4 }}"
                  activate: yes
              redistribute:
                - protocol: static
                  route_map: STATIC
      with_items: "{{ protocols.bgp.neighbors }}"

    - name: save configuration
      ios_config:
        save_when: always
